"""ref

Revision ID: 09d70d331a8b
Revises: f7bf0ff01b47
Create Date: 2023-12-24 14:58:06.196532

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09d70d331a8b"
down_revision: Union[str, None] = "f7bf0ff01b47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("country_currency_fkey", "country", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "country_currency_fkey", "country", "currency", ["currency"], ["id"]
    )
    # ### end Alembic commands ###
