"""ref

Revision ID: 190fd039ab60
Revises: 741abf86edc8
Create Date: 2023-12-24 18:50:33.221729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190fd039ab60'
down_revision: Union[str, None] = '741abf86edc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industry', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('issuer', 'sector',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('issuer', 'industry',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('issuer', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sector', 'id',
               existing_type=postgresql.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sector', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    op.alter_column('issuer', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('issuer', 'industry',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               nullable=False)
    op.alter_column('issuer', 'sector',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               nullable=False)
    op.alter_column('industry', 'id',
               existing_type=sa.String(),
               type_=postgresql.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
