"""init

Revision ID: 194217ae126d
Revises: 
Create Date: 2023-12-24 13:11:49.119808

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "194217ae126d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
