"""ref

Revision ID: 1a6eb18a2272
Revises: 2d8ba7ae6e65
Create Date: 2023-12-24 14:39:36.685167

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a6eb18a2272"
down_revision: Union[str, None] = "2d8ba7ae6e65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("issuer_currency_fkey", "issuer", type_="foreignkey")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "issuer_currency_fkey", "issuer", "currency", ["currency"], ["id"]
    )
    # ### end Alembic commands ###
