"""cb_gdp

Revision ID: 20c6a615e9b6
Revises: 64b5597dc59a
Create Date: 2023-12-24 15:08:45.672290

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c6a615e9b6"
down_revision: Union[str, None] = "64b5597dc59a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "central_bank_rate",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "gdp",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("gdp", sa.DECIMAL(precision=10, scale=9), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gdp")
    op.drop_table("central_bank_rate")
    # ### end Alembic commands ###
