"""ohlc 1dw

Revision ID: 2d8ba7ae6e65
Revises: 50127f3fdb1e
Create Date: 2023-12-24 14:28:48.744414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8ba7ae6e65'
down_revision: Union[str, None] = '50127f3fdb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ohlc_1d',
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=10, scale=9), nullable=False),
    sa.Column('high', sa.String(), nullable=False),
    sa.Column('low', sa.String(), nullable=False),
    sa.Column('close', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['figi'], ['securities.figi'], ),
    sa.PrimaryKeyConstraint('figi', 'date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ohlc_1d')
    # ### end Alembic commands ###
