"""first_date

Revision ID: 3843eaf3037c
Revises: 8bd8d3fe1b44
Create Date: 2024-01-01 14:47:05.327572

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3843eaf3037c"
down_revision: Union[str, None] = "8bd8d3fe1b44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "securities", sa.Column("first_1day_candle_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("securities", "first_1day_candle_date")
    # ### end Alembic commands ###
