"""ref

Revision ID: 433739f57799
Revises: 88227a306b00
Create Date: 2023-12-24 15:01:13.768641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "433739f57799"
down_revision: Union[str, None] = "88227a306b00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ohlc_1d",
        "high",
        existing_type=sa.VARCHAR(),
        type_=sa.DECIMAL(precision=10, scale=9),
        existing_nullable=False,
        postgresql_using="high::numeric(10,9)",
    )
    op.alter_column(
        "ohlc_1d",
        "low",
        existing_type=sa.VARCHAR(),
        type_=sa.DECIMAL(precision=10, scale=9),
        existing_nullable=False,
        postgresql_using="low::numeric(10,9)",
    )
    op.alter_column(
        "ohlc_1d",
        "close",
        existing_type=sa.VARCHAR(),
        type_=sa.DECIMAL(precision=10, scale=9),
        existing_nullable=False,
        postgresql_using="close::numeric(10,9)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ohlc_1d",
        "close",
        existing_type=sa.DECIMAL(precision=10, scale=9),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "low",
        existing_type=sa.DECIMAL(precision=10, scale=9),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "high",
        existing_type=sa.DECIMAL(precision=10, scale=9),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
