"""securities

Revision ID: 50127f3fdb1e
Revises: 70bc525fa62c
Create Date: 2023-12-24 14:09:06.827626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50127f3fdb1e'
down_revision: Union[str, None] = '70bc525fa62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('securities',
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issuer', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer'], ['issuer.id'], ),
    sa.ForeignKeyConstraint(['type'], ['securities_type.id'], ),
    sa.PrimaryKeyConstraint('figi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securities')
    # ### end Alembic commands ###
