"""divid


Revision ID: 64c651e66322
Revises: 00d4a8b7eb06
Create Date: 2024-06-23 12:58:32.647213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64c651e66322"
down_revision: Union[str, None] = "00d4a8b7eb06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "divid",
        sa.Column("figi", sa.String(), nullable=False),
        sa.Column("declared_date", sa.DateTime(), nullable=False),
        sa.Column("last_buy_date", sa.DateTime(), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("dividend_net", sa.DECIMAL(precision=18, scale=9), nullable=False),
        sa.PrimaryKeyConstraint(
            "figi", "declared_date", "last_buy_date", "payment_date"
        ),
    )
    # op.create_foreign_key(None, 'securities', 'securities_type', ['securities_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("divid")
    # ### end Alembic commands ###
