"""issuer table

Revision ID: 70bc525fa62c
Revises: 8f1ea14b88da
Create Date: 2023-12-24 14:01:08.679591

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70bc525fa62c"
down_revision: Union[str, None] = "8f1ea14b88da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuer",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("ipo_date", sa.Date(), nullable=True),
        sa.Column("sector", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("industry", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("currency", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["industry"],
            ["industry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sector"],
            ["sector.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issuer")
    # ### end Alembic commands ###
