"""ref

Revision ID: 741abf86edc8
Revises: 5d847eba2bf5
Create Date: 2023-12-24 18:48:54.964905

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "741abf86edc8"
down_revision: Union[str, None] = "5d847eba2bf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("issuer_country_fkey", "issuer", type_="foreignkey")
    op.drop_constraint("issuer_sector_fkey", "issuer", type_="foreignkey")
    op.drop_constraint("issuer_industry_fkey", "issuer", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "issuer_industry_fkey", "issuer", "industry", ["industry"], ["id"]
    )
    op.create_foreign_key("issuer_sector_fkey", "issuer", "sector", ["sector"], ["id"])
    op.create_foreign_key(
        "issuer_country_fkey", "issuer", "country", ["country"], ["id"]
    )
    # ### end Alembic commands ###
