"""sec_type_type

Revision ID: 818aa682962f
Revises: aa74bb91f908
Create Date: 2024-06-07 16:50:58.941741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818aa682962f'
down_revision: Union[str, None] = 'aa74bb91f908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities_type', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities_type', 'id')
    # ### end Alembic commands ###
