"""ref

Revision ID: 88227a306b00
Revises: 09d70d331a8b
Create Date: 2023-12-24 14:59:13.548155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88227a306b00"
down_revision: Union[str, None] = "09d70d331a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "country",
        "id",
        existing_type=postgresql.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "country",
        "currency",
        existing_type=postgresql.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "currency",
        "id",
        existing_type=postgresql.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "currency",
        "id",
        existing_type=sa.String(),
        type_=postgresql.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "country",
        "currency",
        existing_type=sa.String(),
        type_=postgresql.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "country",
        "id",
        existing_type=sa.String(),
        type_=postgresql.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
