"""ipo

Revision ID: 8bd8d3fe1b44
Revises: f9a4da48249e
Create Date: 2023-12-31 16:01:56.750150

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bd8d3fe1b44"
down_revision: Union[str, None] = "f9a4da48249e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("issuer", "ipo_date")
    op.add_column("securities", sa.Column("ipo_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("securities", "ipo_date")
    op.add_column(
        "issuer", sa.Column("ipo_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
