"""sec_type_type

Revision ID: aa74bb91f908
Revises: aabb5d68ec2e
Create Date: 2024-06-07 16:50:28.070466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa74bb91f908'
down_revision: Union[str, None] = 'aabb5d68ec2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities_type', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities_type', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
