"""exchange

Revision ID: ba8158747de6
Revises: bec216c708b0
Create Date: 2023-12-24 16:02:43.855837

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba8158747de6"
down_revision: Union[str, None] = "bec216c708b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("securities", sa.Column("exchange", sa.String(), nullable=False))
    op.drop_constraint("securities_country_fkey", "securities", type_="foreignkey")
    op.create_foreign_key(None, "securities", "exchange", ["exchange"], ["id"])
    op.drop_column("securities", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "securities",
        sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "securities", type_="foreignkey")
    op.create_foreign_key(
        "securities_country_fkey", "securities", "country", ["country"], ["id"]
    )
    op.drop_column("securities", "exchange")
    op.drop_table("exchange")
    # ### end Alembic commands ###
