"""twittter

Revision ID: bec216c708b0
Revises: a9a801bc1ef7
Create Date: 2023-12-24 15:22:16.318079

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bec216c708b0"
down_revision: Union[str, None] = "a9a801bc1ef7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "twitter",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("related_issuer", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["related_issuer"],
            ["issuer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("twitter")
    # ### end Alembic commands ###
