"""ohlc

Revision ID: c79ca0d08e5c
Revises: 0ab5c9517415
Create Date: 2023-12-30 17:18:51.441122

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c79ca0d08e5c"
down_revision: Union[str, None] = "0ab5c9517415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ohlc_1d",
        "open",
        existing_type=sa.NUMERIC(precision=10, scale=9),
        type_=sa.DECIMAL(precision=10, scale=10),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "high",
        existing_type=sa.NUMERIC(precision=10, scale=9),
        type_=sa.DECIMAL(precision=10, scale=10),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "low",
        existing_type=sa.NUMERIC(precision=10, scale=9),
        type_=sa.DECIMAL(precision=10, scale=10),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "close",
        existing_type=sa.NUMERIC(precision=10, scale=9),
        type_=sa.DECIMAL(precision=10, scale=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ohlc_1d",
        "close",
        existing_type=sa.DECIMAL(precision=10, scale=10),
        type_=sa.NUMERIC(precision=10, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "low",
        existing_type=sa.DECIMAL(precision=10, scale=10),
        type_=sa.NUMERIC(precision=10, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "high",
        existing_type=sa.DECIMAL(precision=10, scale=10),
        type_=sa.NUMERIC(precision=10, scale=9),
        existing_nullable=False,
    )
    op.alter_column(
        "ohlc_1d",
        "open",
        existing_type=sa.DECIMAL(precision=10, scale=10),
        type_=sa.NUMERIC(precision=10, scale=9),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
