"""ref

Revision ID: e10d7dc2e05a
Revises: 0b8b95f0c047
Create Date: 2023-12-24 19:46:19.674746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10d7dc2e05a'
down_revision: Union[str, None] = '0b8b95f0c047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('securities_issuer_fkey', 'securities', type_='foreignkey')
    op.drop_column('securities', 'issuer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('issuer', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('securities_issuer_fkey', 'securities', 'issuer', ['issuer'], ['id'])
    # ### end Alembic commands ###
